name: scrolling_dulu
description: A new Flutter project.
 
 
publish_to: 'none'  

 
 
 
 
 
 
 
 
 
 
 
 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

 
 
 
 
 
 
dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  permission_handler: ^10.4.3

   
   
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  scroll_app_bar: ^2.0.0
  flutter_advanced_networkimage_2: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0
  device_info_plus: ^9.0.2
  autocomplete_textfield: ^2.0.1
  shared_preferences: ^2.2.0
  media_kit: ^1.0.2
  media_kit_video: ^0.0.4
  media_kit_libs_linux: ^1.0.2
  media_kit_libs_android_video: ^1.1.1
  media_kit_native_event_loop: ^1.0.6
  dart_vlc: ^0.4.0
  video_player: ^2.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

   
   
   
   
   
  flutter_lints: ^2.0.0

 
 

 
flutter:

   
   
   
  uses-material-design: true

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
