# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
           flutter-version: '3.7.7'
           channel: 'stable'
      - name: Depends
        run: flutter pub get
      - name: run test
        run: flutter test
      - name: Analyze project source
        run: flutter analyze
      - name: install depends linux 
        run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev
         
      - name: building linux   
        run: flutter build linux
        
      - name: building android
        run: flutter build apk --release
